project:
  type: website
  output-dir: docs
  preview: 
    port: 4200
    watch-inputs: true

website:
  title: "Oliver Saal"
  
  navbar:
    background: primary
    search: true
    left: 
      - text: "Me"
        file: index.qmd
      - text: "Research"
        file: research.qmd
      - text: "Teaching"
        file: teaching.qmd
      - text: "Resources"
        file: resources.qmd
      - text: "Thinking Out Loud"
        file: blog.qmd
    right:
      - icon: twitter
        href: https://twitter.com/ollisaal
      - icon: github
        href: https://github.com/osaal
      - icon: envelope
        href: mailto:oliver.saal@proton.me
  
  sidebar:
    - title: "Me"
      style: "docked"
      contents:
        - text: "Home"
          file: index.qmd
        - text: "Curriculum Vitae"
          file: about.qmd
    - title: "Research"
      contents:
        - text: "Research"
          file: research.qmd
        - text: "Master's Thesis"
          file: mathesis.qmd
  cookie-consent: 
    type: express
    style: simple
    palette: light

format:
  html:
    theme: flatly
    css: styles.css
    toc: true