---
title: "Research"
---

These pages contain my research, with publication links and other contents as available. Data will be added when possible.

Please reference the original sources, not this website.

*Updated 10 July 2025*

## Current Research Project
-   [Project on determining the service needs of emergency services at the regional welfare counties](https://intermin.fi/hankkeet/hankesivu?tunnus=SM013:00/2025) Senior specialist in research project at Finnish Ministry of the Interior. Financing by the Fire Safety Fund (Palosuojelurahasto).

## Past Research Projects

-   [*Emergency Services Zero Tolerance to Discrimination and Harassment - Fact or Fiction?*](https://pelastusopisto.fi/nollatoleranssi) Project manager and principal investigator of research project at Pelastusopisto - Emergency Services Academy Finland. Financing by the Fire Safety Fund (Palosuojelurahasto).

## Research Publications

### Peer-Reviewed Articles

Helander, Mika & Saal, Oliver. 2025. *Evaluating the Effects of Globalization on Work: Building upon Awareness, Learning, and Knowledge*. *Nordic Journal of Working Life Studies* 2025(3). OnlineFirst. Link: <https://doi.org/10.18291/njwls.151853>.

Saal, Oliver, Iida Silfverhuth & Konsta Huovinen. 2024. *Epäasiallisen ja väkivaltaisen kohtelun suomen- ja ruotsinkielisen mittarin validointi pelastus- ja ensihoitoalalla*. \[*Validation of Finnish and Swedish Language Instrument on Inappropriate and Violent Behaviour in the Rescue and Emergency Services*\]. Registered report. Stage 1 evaluation complete. State 2 under peer review. Temporarily available: <https://www.jyu.fi/fi/tutkimus/julkaiseminen-jyvaskylan-yliopistossa/rekisteroidyt-tutkimusraportit-valmistuneet-arviot>.

### Chapters in Edited Volumes

Johanson, Jan-Erik, Alisa Puustinen & Oliver Saal. 2024. *Ignorance is Bliss? Network Analysis Shaping our Understanding of Security Risk Perceptions*. In Petri Uusikylä, Harri Jalonen & Annukka Jokipii (eds.). "Information Resilience and Comprehensive Security: Challenges and Complexities in Wicked Environments". Palgrave Macmillan. Link: <https://link.springer.com/book/9783031661952>.

### Reports

Saal, Oliver, Iida Silfverhuth, Konsta Huovinen, Aino Harinen, Riikka Salmi, Janne Koivukoski & Mimmi Tolvanen. 2025. *Tulta ilman savua. Epäasiallinen ja väkivaltainen kohtelu pelastusalalla ja ensihoidossa*. \[*Fire without Smoke: Inappropriate and Violent Behaviour in the Rescue Services and Emergency Medical Care*. Research report.\] Kuopio: Pelastusopisto. Link: <http://info.smedu.fi/kirjasto/sarja_B/B6_2025.pdf>.

Saal, Oliver & Alisa Puustinen. 2023. *Suomalaisten pelastusasenteet 2023*. \[*Finnish Emergency Services Attutides 2023*. Research report.\] Helsinki: Ministry of the Interior. Link: <http://urn.fi/URN:ISBN:978-952-324-944-8>.

Saal, Oliver, Aino Harinen & Alisa Puustinen. 2021. *Suomalaisten pelastusasenteet 2020*. \[*Finnish Emergency Services Attitudes 2020*. Research report.\] Kuopio: Finnish Emergency Services Academy. Link: <http://info.smedu.fi/kirjasto/Sarja_B/B2_2021.pdf>.

### Theses

Saal, Oliver. 2020. *Legitimating Academic Practice: Mapping the Diversity of Epistemic Logics in Finnish University Disciplines*. \[Master's Thesis.\] Åbo Akademi University, Turku, Finland. Link: <https://www.doria.fi/handle/10024/176872>.

Saal, Oliver. 2018. *Interaction between Online and Offline Worlds. Gender and Ethnicity Processes in the Online Roleplaying Game* World of Warcraft. \[Bachelor's Thesis.\] Åbo Akademi University, Turku, Finland.

### Unpublished Manuscripts

Saal, Oliver, Iida Silfverhuth & Konsta Huovinen. n.d. *Pelastajien ja ensihoitajien kokema epäasiallinen ja väkivaltainen kohtelu - systemaattiseen kirjallisuuskatsaukseen pohjautuva käsiteanalyysi ja esiintyvyyden meta-analyysi. \[Inappropriate and Violent Behaviour in the Rescue and Emergency Services: A Conceptual Analysis and Meta-Analysis of Prevalence Based on a Systematic Literature Review\].* Submitted for peer review in *Työelämän tutkimus*. \[Article manuscript.\]

## Conference Proceedings

*Pelastustoimen palvelutarpeen määrittelyn tutkimushankkeen eteneminen \[Progress report of the research project for determining the service needs of emergency services at the regional welfare counties\]*. With Tiina Etelälahti and Jaana Määttälä. Emergency Services Research Days 2025, working group Communications and Information Leadership. 11 June 2025. Unpublished.

*Pelastusalan ja ensihoidon kohtaaman epäasiallisen kohtelun muodot ja puuttumiskeinot: Valtakunnallisen kyselytutkimuksen tuloksia \[The Forms and Interventions for Inappropriate Behaviour in the Emergency Services and First Aid: Results from a national survey study\]*. Work Research Days 2024, working group Problematic Interactions in Work Life. 7 November 2024. Unpublished.

*Yksilön riskikäsitysten ja omatoimisen varautumisen kausaalisuhteen merkitys kokonaisturvallisuudelle \[The Relevance of the Causal Connection between an Individual's Risk Perception and Self-Preparedness for Total Security\]*. Sociology Days 2024, working group Sociology of Safety and National Defense. 21 March 2024. *Sosiologia* *61*(2), 171.

*Pelastusalalla ja ensihoidossa esiintyvä syrjintä ja häirintä oikeuksien toteutumisen näkökulmasta* \[*Discrimination and harassment in the rescue services and out-of-hospital emergency health care from the perspective of the fulfilling of rights\]*. With Iida Silfverhuth and Konsta Huovinen. Sociology Days 2024, working group Fulfilling of Rights in the Welfare State. 21 March 2024. *Sosiologia 61*(2), 157.

*Yhdessä eteenpäin...? Työryhmäkeskustelu turvallisuustutkimuksen yhteistyön organisointimahdollisuuksista* \[*Forward together...? Working Group Discussion on the Organisational Possibilities of Collaboration in Safety and Security Research*\]. With Alisa Puustinen. Conference on Administrative and Local Government Studies 2023, working group Safety and Security Studies. 17 November 2023. Unpublished.

*Riskitodennäköisyys ja verkostoanalyysi* \[*Risk Probability and Network Analysis*\]. With Alisa Puustinen. Sociology Days 2023, working group Sociology of Safety and National Defense. 24 March 2023. *Sosiologia* *60*(2), 145.

*The Phenomenological Structure of Scientific Disciplines*. Draft chapters of doctoral thesis. Finnish Symposium for Science and Technology Studies, 8 July 2022. Unpublished.

*The Phenomenology of Scientific Disciplines: Boundaries, Meanings, and Relevance*. Sociology Days 2022, working group Science, Technology and Society. 25 March 2022. *Sosiologia 59*(2), 174.

*Uhkien ja riskien koettujen todennäköisyyksien jäsentäminen* \[*Conceptualising Perceived Probabilities of Threats and Risks*\]. With Alisa Puustinen. Sociology Days 2021, working group Sociology of Safety and National Defense. 12 March 2021. *Sosiologia 58*(2), 202.

*Evaluating the Effects of Globalisation on Work*. With Mika Helander. Sociology Days 2021, working group Global Sociology. 11 March 2021. *Sosiologia 58*(2), 180.

## Conference Organising

Working group *Communications and Information Leadership* at the Emergency Services Research Days 2025, 11 June 2025, Kuopio, Finland. With Päivi Mäkelä (Pelastusopisto - Emergency Services Academy Finland). Link to conference website: <https://www.pelastusopisto.fi/tutkimus-ja-kehitys/pelastustoimen-tutkimuspaivat/pelastustoimen-tutkimuspaivat-2025/>

Working group *Sociology of Security and National Defense* at the Sociology Days 2024, 21-22 March 2024, Kuopio, Finland. With Miina Kaarkoski (National Defense University). Link to conference website: <https://sosiologipaivat.fi/annual-conference-2024/>

Working group *Safety and Security Studies* at the Conference on Administrative and Local Government Studies 2023, 16-17 November 2023, Turku, Finland. With Alisa Puustinen (Ministry of the Interior), Brita Somerkoski (University of Turku) & Päivi Mäkelä (Pelastusopisto). Link to conference website: <https://www.abo.fi/en/hktp2023/>

## Research Financing

-   **Kone Foundation** \| Personal working grant for doctoral thesis in Sociology. 3.5 years (full-time). Awarded in 2021.
-   **Waldemar von Frenckell Foundation** \| Personal working grant for doctoral thesis in Sociology. 5 months (full-time). Awarded in 2021.

## Community Service

Peer reviewer for the [Yearbook of Emergency, Safety and Security Studies](https://www.pelastusopisto.fi/kirjasto-ja-tietopalvelut/julkaisut-ja-aineistot/pelastus-ja-turvallisuustutkimuksen-vuosikirja/), volume 2025.

## Non-Fiction Writing

### Articles

Saal, Oliver. 21.9.2024. *HSL-yhtymän perussopimus painottaa liikaa taloutta* \[*The Base Contract of the HSL Alliance Overemphasizes the Economy*\]. Helsingin Sanomat. Link: <https://www.hs.fi/mielipide/art-2000010707993.html>.

Saal, Oliver & Puustinen, Alisa. 2023. *Suomalaiset ovat tyytyväisiä pelastustoimintaan - mutta osaavatko he itse toimia vaaratilanteissa?* \[*Finns are satisfied with emergency services - but do they know how to act in risky situations?*\]. *Palopäällystö* 2/2023: 29. Link: <https://issuu.com/palopaallysto/docs/palopaallysto-lehti-2_2023>.

### Blog Posts

Saal, Oliver. 2025. *Tasa-arvoon ja yhdenvertaisuuteen tähtäävät toimenpiteet purevat osittain*. \[*Interventions Aiming at Equality and Inclusion are Partially Effective*\]. *Pelastusopiston blogi*, 15.1.2024. Link: <https://www.pelastusopisto.fi/blogi/tasa-arvoon-ja-yhdenvertaisuuteen-tahtaavat-toimenpiteet-purevat-osittain/>.

Saal, Oliver. 2024. *Epäasiallisuuksia ja väkivaltaa ei raportoida, jos ilmoitusjärjestelmää ei ole olemassa*. \[*Inappropriate Behaviour and Violence is Not Reported if There is No Reporting System*\]. *Pelastusopiston blogi*, 18.12.2024. Link: <https://www.pelastusopisto.fi/blogi/epaasiallisuuksia-ja-vakivaltaa-ei-raportoida-jos-ilmoitusjarjestelmaa-ei-ole-olemassa/>.

Saal, Oliver. 2024. *Työyhteisön epäasiallisuudet ja väkivalta heikentävät alan pitovoimaa*. \[*Inappropriate Behaviour and Violence Weakens Workplace Retention*\]. *Pelastusopiston blogi*, 13.11.2024. Link: <https://www.pelastusopisto.fi/blogi/tyoyhteison-epaasiallisuudet-ja-vakivalta-heikentavat-alan-pitovoimaa/>.

Saal, Oliver. 2024. *Epäasiallisuutta ja väkivaltaa esiintyy pelastusalalla ja ensihoidossa laajasti*. \[*Inappropriate and Violent Behaviour is Commonplace in Firefighting and Emergency Medicine*\]. *Pelastusopiston blogi*, 16.10.2024. Link: <https://www.pelastusopisto.fi/blogi/epaasiallisuutta-ja-vakivaltaa-esiintyy-pelastusalalla-ja-ensihoidossa-laajasti/>.

Saal, Oliver; Iida Silfverhuth & Konsta Huovinen. 2024. *Kesäisiä terveisiä Nollatoleranssi-hankkeesta!* \[*Summer greetings from the Zero Tolerance project!*\]. *Pelastusopiston blogi* 25.6.2024. Link: <https://www.pelastusopisto.fi/blogi/kesaisia-terveisia-nollatoleranssi-hankkeesta/>.

Saal, Oliver. 2024. *Pelastusalalla epäasiallista käytöstä tulee alan sisältä ja sen ulkopuolelta* \[*The Emergency Services Meets Inappropriate Behaviour from Within and Without*\]. *SPAL:in Turvallisuuden tekijät -blogi*, 22.2.2024. Link: <https://www.spal.fi/blogs/pelastusalalla-epaasiallista-kaytosta-tulee-alan-sisalta-ja-sen-ulkopuolelta/>

Saal, Oliver. 2024. *Avoin tiede pelastusalan arvostuksen kohottojana* \[*Open Science as a Positive Influence on the Respect of the Emergency Services*\]. *Pelastusopiston blogi* 5.2.2024. Link: <https://www.pelastusopisto.fi/blogi/avoin-tiede-pelastusalan-arvostuksen-kohottajana/>.
