---
title: "Teaching"
---

These pages contain summaries of my teaching experience, materials, pedagogical projects, and other related musings.

University courses in Finland are divided into three levels:

1.  Basic: Introductory courses, as part of short minor subject (25 ECTS) or first- through third-year major studies, typically Bachelor level students.
2.  Intermediate: More in-depth courses, as part of long minor subject (50-70 ECTS) or second- and third-year major studies, typically Bachelor level students.
3.  Advanced: Graduate courses, as part of Master's studies.

## Teaching Experience

### Taught courses

Quantitative Methods. Period I/23. Pelastusopisto - Emergency Services Academy Finland. 2 ECTS.

Advanced Sociological Theory 1: Science and Technology Studies. Period II/22. Åbo Akademi University. 5 ECTS. [Link to curriculum](https://studiehandboken.abo.fi/en/course/380201.1/1293?period=2022-2024)

### Lectures and workshops

**2022**

*How to Choose Statistical Method?* Advanced Sociological Methods 2. Advanced level. Åbo Akademi University.

*Statistical Inference*. Advanced Sociological Methods 2. Advanced level. Åbo Akademi University.

*Workshop in Statistical Inference*. Advanced Sociological Methods 2. Advanced level. Åbo Akademi University.

*Sociology of Education*. Basic Course in Sociology: Society's Structures and Institutions. Basic level. Åbo Akademi University.

**2021**

*Who Researches the Researcher? Science Studies and Knowledge Practices at the Finnish University*. Current Sociological Research. Basic level. Åbo Akademi University.

*Logistic Regression*. Advanced Sociological Methods: Quantitative Methods. Advanced level. Åbo Akademi University.

*General Linear Models and OLS Regression*. Advanced Sociological Methods: Quantitative Methods. Advanced level. Åbo Akademi University.

*Statistical Inference*. Advanced Sociological Methods: Quantitative Methods. Advanced level. Åbo Akademi University.

**2020**

*Who Researches the Researcher? Science Studies and Knowledge Practices at the Finnish University*. Current Sociological Research. Basic level. Åbo Akademi University.

*General Linear Models*. Advanced Sociological Methods: Quantitative Methods. Advanced level. Åbo Akademi University.

*Statistical Inference*. Advanced Sociological Methods: Quantitative Methods. Advanced level. Åbo Akademi University.

*Group workshops*. Basic Course in Sociology: The Individual and Society. Basic level. Åbo Akademi University.

*Bias Analysis in OLS Regression*. Workshop. Åbo Akademi University, Sociological Unit.

**2019**

*General Linear Models*. Advanced Sociological Methods: Quantitative Methods. Advanced level. Åbo Akademi University.

*Group workshops*. Basic Course in Sociology: The Individual and Society. Basic level. Åbo Akademi University.

### Formal Pedagogical Education

Pedagogy for Subject Teachers (20 ECTS):

-   *Pedagogical Psychology* (5 ECTS, 2016)
-   *Applied Pedagogy and Societal Development* (5 ECTS, 2015)
-   *Didactics* (5 ECTS, 2015)
-   *Special Needs Education* (5 ECTS, 2015)
