---
title: "Grant Us the Strength - And Maybe Also Healthcare?"
description: "Thoughts on the early career researcher financing model in Finland."
author: "Oliver Saal"
date: "3/21/2023"
date-modified: last-modified
draft: false
citation:
  url: https://osaal.github.io/posts/fuurtecrmeeting.html
citation-location: document
reference-location: margin
bibliography: references.bib
categories:
  - advocacy
  - science policy
  - early career researchers
  - english
---

Thursday 16 March, I attended my first meeting with the Early Career Researchers' committee of the [Finnish Union of University Researchers and Teachers, FUURT](https://tieteentekijat.fi/en/home/). I thought the occasion would be a good way to inaugurate this blog - with a stream-of-thought post. Coherent thoughts not guaranteed.

The ECR committee is composed of representatives from most Finnish universities, this year eleven out of fourteen universities are represented. The representatives are all early career researchers, spanning from first-year doctoral researchers to established post docs. I was struck by the variety of disciplines, universities, and career paths in this year's committee - we even have a representative from outside the university, which speaks to the multiple career pathways of post docs.

The majority of the meeting was spent in discussing current events at the universities. Topics spanned work contract disputes, information pathways, grant writers, funding problems, salary system disparities, change negotiations and layoffs, new researchs on doctoral researchers' inequalities of opportunity, and so on.

If I were to summarise the main takeaways from the meeting, it would be this: the problems of doctoral students country-wide stem mostly from insecure funding. Again and again, the topic of funding rose up: whether it was the University of Oulu negotiating automatic 10 per cent part-time work contracts for grant researchers, the Ministry of Education and Culture pushing for a shortened doctoral track and interest organisations protesting due to the lack of funding, or the University of Turku laying off 50 people and pushing the rest harder on securing external financing, it all came back to money.

The topic I want to work on in this committee, and more general in science policy, is indeed this problem of financing. Finland follows a very peculiar model of doctoral financing, where a large portion of the funding stems from private foundation grants. While this system allows for a certain flexibility in funding opportunities and specialised research, it also presents major problems.

Firstly, the disparity between grant and salary income levels is far too wide. The average monthly grant size depends on the discipline - itself a questionable aspect! - but varies between 2 100 euros and 2 400 euros gross [@siekkinen2021]. Meanwhile, the minimum recommended starting salary for doctoral researchers in the general collective agreement is 2 200 euros, rising up to a recommended minimum of 2 800 euros in the final stretch of the dissertation process[^1]. Granted, these are recommendations - and not, for instance, followed at my home university - but the possible disparity is large. It is noteworthy, that in either case, doctoral researchers make considerably less than the average Finnish salary for a person with a Master's degree (the prerequirement for doctoral studies in Finland), regardless of field.

[^1]: General Collective Agreement for Universities, 1 Aug 2022-31 Mar 2024, available [here](https://www.sivista.fi/wp-content/uploads/2022/06/Yo-tes-1.8.2022-31.3.2024-final_EN.pdf). Retrieved 21 March 2023.

If this gross income disparity was not enough, there is the problems of work benefits. Grant researchers are not employed by anyone, meaning that they lack access to work benefits such as work-provided healthcare. With the current state of the Finnish public healthcare system, privately organised work healthcare is the only reasonable course of action. Considering that a large number of doctoral researchers suffer from mental health issues (themselves related to funding stresses in part!), this access would be crucial [see e.g., @guthrie2017]. Work healthcare also conducts pre-emptive check-ups to a much greater extent than public healthcare, which allows for early recognition of burnout, depression, anxiety, and other such work-related illnesses that arise in the academy. Of course, this healthcare is available to individuals outside a work healthcare agreement, too - if they pay out of pocket or have an insurance policy that covers such expenses. Hardly a viable option for the well-below-median income of a grant researcher, many of whom have families to sustain.

There is also the curious problem of taxation. Private research grants in Finland are exempt from taxation (except for a few obligatory health care and public broadcasting-related fees, totaling a few per cent of the income) up to a certain threshold, adjusted yearly by the government. Currently, this threshold is approximately 25 000 euros gross, meaning that most grants fall just below this threshold. Taxes accrue only on the part crossing the threshold. This is, in theory, a just system, but the problems arise when considering tax rebates. Simply put: if you pay no taxes, you get no rebate. This means no deductions for having a home office, no deductions for work-related expenses like literature, no work travel deductions. All of these deductions are, in general, available to salaried researchers, as they inevitably pay some level of tax on their salary.

I cannot say the exact numbers (and I would love to see an economist work through them!), but these multiple disparities compound to make the net income of a grant researcher considerably lower than that of a salaried doctoral researcher. There are, however, a few attempts at solving this.

University of Eastern Finland was the first university in Finland to enact a university-wide policy of automatically salarying *every* grant researcher, regardless of position, [with a 10 % part-time work contract](https://www.uef.fi/en/article/uef-takes-a-significant-step-to-improve-the-status-of-grant-funded-researchers-through-part-time). This enables grant researchers access to work healthcare and other resources, as well as places them legally in a similar position as other salaried researchers. This contract is only available for researchers with grants lasting at least one year, but the practice of giving working grants shorter than a year should regardless be discontinued, due to the major discontinuities such practices create.

UEF enacted this policy in the summer of 2021, and it has since spread to the University of Oulu as well, with the University of Lapland currently negotiating conditions for such a policy. Oulu is, however, struggling with scenarios where group leaders retain veto rights to drafting contracts (argued to be related to budget-balancing necessities), which places grant researchers in unequal positions.

Another option, and one that I have not seen discussed before, is to raise grant sums above the taxable limit. This would require more precise calculations as to where a reasonable equilibrium lies - how much more should a grant researcher make to enable necessary tax rebates? This does present a new problem: as doctoral student intake has been growing year by year the past decades, increasing grant sizes exacerbates the already major problem of many researchers being left without grants, as well as risks shortening average grant lengths.

In total, the problem seems to me to be more a problem of how research financing is currently structured. Private grants are, I would argue, not a reasonable, effective, or fair and balanced way to run the doctoral-industrial complex. Foundations give out grants from their investment surplus, and if the pressure to give larger total sums increases, so will inevitably questionable investment practices become more commonplace. The most profitable investments are the most egregious and the ones at risk of (accidentally or purposefully) supporting human rights violations in the Global South.

Thus, one solution lies in increased public research expenditure, together with direct coupling of expenditure and doctoral education. If we want to produce more and more doctors every year, we need more and more money every year. The old dynasties of Kone, Hartwall, and Erkko should not be in charge of financing Finnish research excellence - the public should.
