---
  title: "Among the Firefighters"
description: "I spent the past half a year doing safety and security studies research. This blog is about that experience."
author: "Oliver Saal"
date: "6/21/2023"
date-modified: last-modified
draft: false
citation:
  url: https://osaal.github.io/posts/safetyandsecuritystudies.html
language: fi
citation-location: document
reference-location: margin
bibliography: references.bib
categories:
  - research
  - safety studies
  - security studies
  - Pelastusopisto Emergency Services Academy Finland
  - english
---

Tired and wrung dry, I walked out of the concrete-and-glass main building of the Emergency Services Academy, Pelastusopisto, today. After a hectic month of our annual conference, two days of sessions on risk management, new technologies in forest firefighting, emergency services communications, and many more topics, my current work contract is coming to an end. Luckily, and very surprisingly, I was offered continuation for another half a year. This blog is about the experience of working here, of working in safety and security research, and of working as a public sector researcher.

# Pelastusop--what?

"[Pelastusopisto - Emergency Services Academy Finland](https://www.pelastusopisto.fi)"[^1] organises the national emergency services education in Finland, from 'run-of-the-mill' firefighters to civil protection specialists, emergency responders, and emergency services leadership personnel. It is financed and governed by the Ministry of the Interior, and functions as a specialist school following its own educational regulation, separate from regular second and third cycle educational institutions. Crucial to my own interests, however, it also coordinates, organises, and supports national research into emergency services - something I will collectively call 'safety and security research.'

[^1]: Yes, that's the full name. I'll use a shortened name henceforth.

Originally, I found myself in the inland lake city of Kuopio[^2] at the Emergency Services Academy in late 2020, as I graduated amidst the COVID19 pandemic and was looking for odd jobs while searching for PhD research funding. I received a position as a research assistant and was tasked primarily with completing the Finnish Attitudes of Emergency Services 2020 report, a triannual survey study on Finnish attitudes towards the emergency services, risk preparedness and personal preparation behaviour, emergency communications preferences, among other topics. The job was short, and I finished the four-month stint visiting the campus only once, even mailing my computer and keys back to Kuopio.

[^2]: As a native to the southern Finnish shorelines and archipelagos, I find myself surprisingly at home in this in-land city of 120 000 inhabitants, thanks to its vast lakes and island belts. Though, they speak a funny accent here.

However, I was quite taken aback to be asked to return some two-and-a-half years later, this time as a researcher, to once again complete the Attitudes report for 2023. The job title was fancier, the salary higher, and the contract longer, and the offer came at a time where I was stuck in a rut with my PhD thesis. The change was welcome, in other words. I took up a part-time position for the tail-end of 2022, finishing up my course in Science and Technology Studies and other odd ends of my thesis at Åbo Akademi University before returning once more to the concrete, rather monolithic and imposing main building[^3] in southern Kuopio.

[^3]: Seriously, the architecture is impressive. Apparently constructed in 1992 as a [winning design](http://arksavo.fi/kohteet/pelastusopisto/) in an architectural competition, the campus is composed on multiple concrete buildings, all in various angles to another, with intersecting buildings. My first thought was "Jesus H. Christ, that is *awful!",* but it has definitely grown on me over the past half year.

# Interdisciplinarity in Action

The research conducted at Pelastusopisto is very varied. I came on-board as a social scientist, working with my colleague senior researcher and docent [Alisa Puustinen](https://mpkk.academia.edu/AlisaPuustinen) to conduct a nationally representative attitude and knowledge survey study. However, one of my most striking memories must have been one of our monthly on-location days, where our colleague [Marjaleena Aatamila](https://scholar.google.fi/citations?user=5ymRewEAAAAJ&hl=fi) presented her research on carcinogen exposure during cooktop burning of a selection of household materials, conducted in co-operation with Aalto University[^4]. As she was presenting parts-per-million measurements of various aldehydes and the rate of change over time as the testing space was aired out, I thought to myself, "I am far away from my sociological home!"

[^4]: [Information in Finnish](https://www.pelastusopisto.fi/tutkimus-ja-kehitys/hankkeet/liesipalojen-syttyminen-vaikutukset-ja-ehkaisy/), as well as a [blog in English](https://blogs.aalto.fi/fire/liesipalo/) by Aalto University, on the project.

My first point is, indeed, the utter joy of working in such an interdisciplinary group. Apart from me as a sociologist, our researchers are everything from administrative scientists and communications researchers to biologists, pharmacists, physicists, and statisticians. Despite these, we work across borders, co-operating and helping each others in projects we might never have a chance to otherwise conduct. The traditional boundaries between soft and hard, qualitative and quantitative, exact and approximate were constantly blurred, and all our research was better from this diversity of perspectives.

Another signal of this interdisciplinarity was how many of us *never actually studied anything remotely related to emergency services!* Many of us were educated in completely different fielda, finding our way to security and safety research by happenstance. In fact, there is no real educational pathway to becoming a safety and security scientist in Finland - apart from, perhaps, a doctorate in military sciences at the National University of Defense, which none of us had or even particularly aspired to have.

Yet, there is an odd camaraderie in the air among security researchers. We discussed this over the conference dinner among colleagues, and came to the conclusion that the common goal and clearly shared values is a major factor in this. As a sociologist, it has been hammered into me over years of brainwa- education, that most topics have multiple perspectives and often divergent values attached to them. Yet, in embodied practice, as I stand discussing the need for context-sensitive education on home preparedness with a conference attendee, the point of divergent values is hard to argue.

Emergency services, and safety research in general, strives to save lives, protect citizens, and create safety. If sociological research can sometimes feel like meaningless word salad[^5], this particular field is hard to view that way. Sure, the odd militarist who speaks of weaponized national defense as part of security-making might be off-putting to those of a more pacifist stint, but it is easy to re-discover one's calm among colleagues discussing the criticalities of securitization discourses and the need for soft values and human understanding in authority practice.

[^5]: I should know, I study social phenomenology.

However, this camaraderie can unfortunately be short-lived. When working in an interdisciplinary field whose institutional status is precarious[^6] and vague, I noticed the distinct lack of inter-departmental communication and network-building. While the Emergency Services Academy is designated as the national coordinator of emergency services research, there is no real connection between all the institutions, both academic and professional, conducting safety and security research in Finland. Many want change to this, but given that most of us work in the public sector, the hinders of a results-driven and highly economized administration may often prove unsurmountable. We lack a common journal, which just adds to the diffusion of research personnel and resources around the country. I would also like to bring up those conducting safety and security research at miscellaneous departments and units across the country, but whose work we rarely see, as the Government Peoples never stray too far into the Murky Shadows of Non-Government Peoples.

[^6]: We are, I concede, financed directly by a ministry. I speak more of the institutional position that emergency services research currently holds, especially in the aftermath of a major social and health care reform.

Perhaps this will change soon, however. The newly-unveiled topic for next years conference is (freely translated) 'Effecting Change Together,' combining questions of research impact with togetherness and networking. One of the strategic aims of Pelastusopisto is to construct a national network of emergency services researchers. Perhaps that ambition is too small: there are enough of us to construct a network of safety and security researchers from all fields, covering topics such as youth marginalisation, health care safety, firefighting and emergency response, armed conflict resolution, international law, the list goes on.

This brings me to the topic more generally. I still am somewhat unclear on what 'safety and security research' even means. At its core, however, it seems to be about the understanding of factors related to safety, from the micro to the macro, and how we can effect change which measurably increases safety - whether it be among the population at large, among firefighters in their professional lives, among civilians caught in armed conflicts, among refugees and immigrants. This opens up for uncountable interesting research streams, even (and especially) in the field of social and human sciences. How do people construct a sense of safety? Which actions can a government take to increase safety, both perceived and real? What dangers lie in focussing on perception over actual safety, and what does it even mean to perceive something as 'safe' or 'dangerous?'

# A Meager, but Very Happy, Conclusion

All of this is more or less an ode to joy. I found this community of stray researchers, many in-between academic homes, looking for an institution to house them. In them, I found camaraderie and true interdisciplinarity, in a way I have only seen described in lengthy papers before. It is this community which is so utterly important for the continued well-being of young researchers: the possibility to walk into an office[^7] and be inspired by the creativity, the variety, and the tenacity of researchers from all across the scientific spectrum.

[^7]: Not a given for Finnish doctoral researchers, unfortunately!

My time at Pelastusopisto has been incredibly rewarding - and as luck would have it, I am given a chance to continue that time. In a sense, I hope I can inspire other doctoral students to look out for these places: the one's that inspire, the one's that support and the one's that push you forward. Academic work can be grueling and thankless - not to talk about the abysmal salaries - so treat yourself, and find a community that supports you.
